### ISSUE TITLE
Assistants API require additional headers

### ISSUE THREAD

**Issue by he9lin** [zio/zio-openai#137]
Hi, first of all, thanks for creating the library. 

I have a question. Since the [Assistant API](https://platform.openai.com/docs/assistants/overview) requires adding `OpenAI-Beta: assistants=v1` to the request. I'm wondering what would be the best way to add it using this library. 

Thanks!

**Comment by vigoo** [comment]
Hi! Seems like the OpenAPI specs the library is generated from does not have this information (https://github.com/openai/openai-openapi/blob/master/openapi.yaml)

But we can add it as a hardcoded rule - there are other hardcoded divergences from the official spec already.

**Comment by he9lin** [comment]
Thanks for the response. If I create a http client layer that will add `OpenAI-Beta: assistants=v1` header to all its requests and use that layer as the http client dependency for all `Assistants` related requests. Would that work as a temporary solution for me? Sorry if that doesn't make any sense as I'm fairly new to ZIO.

**Comment by he9lin** [comment]
Just an update to this. The following is an easy workaround. So I'll just close this issue. 
```scala
val myClient = Client.default.map { client =>
  client.update(_.addHeader("OpenAI-Beta", "assistants=v1"))
}
// ...
program.provide(myClient >>> Assistants.live)
```
