### ISSUE TITLE
How to use behind a proxy?

### ISSUE THREAD

**Issue by nemoo** [zio/zio-openai#31]
Currently I set the proxy as VM options like this: 
-Dhttp.proxyHost=10.0.2.2 -Dhttp.proxyPort=3128 -Dhttps.proxyHost=10.0.2.2 -Dhttps.proxyPort=3128

zio openai calls still fails with: 
timestamp=2023-04-07T09:09:31.366204661Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" java.lang.Exception: Unknown(io.netty.channel.ConnectTimeoutException: connection timed out: api.openai.com/104.18.7.192:443)

When I call the openai api directly via the lihaoyi requests scala library with the same VM options, it works fine.

I am using zio-openai via: https://github.com/kitlangton/automaton

How should I configure the proxy?

**Comment by vigoo** [comment]
ZIO OpenAI is using zio-http to call the OpenAI API. The `default` layers are hiding this by using zio-http's `Client.default` layer but you can provide your own `Client` to the `live` layers, for example (with zio-http 0.0.5 - latest snapshot is different):

```scala
def program: ZIO[Completions, Nothing, Unit] = ???

program.provide(
  ClientConfig.live(
    ClientConfig().proxy(Proxy(url, credentials, headers))
  ),
  Client.fromConfig,
  Completions.live
)
```

**Comment by nemoo** [comment]
I tried to incorporate your suggestions, but it still does not work.  The error I get: 
```
timestamp=2023-04-12T08:48:48.974431188Z level=ERROR thread=#zio-fiber-0 message="" cause="Exception in thread "zio-fiber-4" java.lang.Exception: Unknown(io.netty.channel.ConnectTimeoutException: connection timed out: api.openai.com/104.18.7.192:443)
```

This is what I have: 
```
  val run: ZIO[Any, Throwable, Unit] = {
    val url: URL = URL.fromString("http://10.0.2.2:3128")
      .toOption
      .getOrElse(URL.empty)
    println(s"url: "  + url )
    val proxy = Proxy(url)
    ChatService
      .prompt[ActionService]("What is 1 + 1?" )
      .provide(
        ChatService.live[ActionService],
        ActionService.layer,
        ClientConfig.live(
          ClientConfig().proxy(proxy)
        ),
        Client.fromConfig
      )
  }
```

So it seems that even though I provided the ClientConfig, it is not really taken into consideration. How could I debug it?
